name: SandBox CI

on: [push, pull_request]

jobs:
  _SandBox_Cpp_CI:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir DeliveryManager.client/build
    - name: Compile
      working-directory: DeliveryManager.client/build
      run: |
        cmake ..
        make
    - name: Run program
      working-directory: DeliveryManager.client/build
      run: ./SandBox
    - name: Run tests
      working-directory: DeliveryManager.client/build
      run: ctest -V
